GRAPHQL_URL_ENV_VAR = 'GRAPHQL_URL'
GRAPHQL_API_KEY_1_ENV_VAR = 'GRAPHQL_API_KEY_1'
GRAPHQL_API_KEY_2_ENV_VAR = 'GRAPHQL_API_KEY_2'

AWS_ACCESS_KEY_ID_ENV_VAR = 'AWS_ACCESS_KEY_ID'
AWS_ACCESS_SECRET_ENV_VAR = 'AWS_ACCESS_SECRET'
AWS_S3_BUCKET_NAME = 'AWS_S3_BUCKET'
AWS_REGION_NAME = 'AWS_REGION'

DISCORD_WEBHOOK = 'DISCORD_HOOK'


MAX_RETRIES = 10
