"""created chain_rewards table

Revision ID: 05bb77c45950
Revises: c744d9011218
Create Date: 2023-05-07 13:16:15.895630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "05bb77c45950"
down_revision = "c744d9011218"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chain_rewards",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("chain", sa.String(), nullable=False),
        sa.Column("total_relays", sa.BigInteger(), nullable=False),
        sa.Column("total_pokt", sa.BigInteger(), nullable=False),
        sa.Column("staked_nodes_avg", sa.BigInteger(), nullable=False),
        sa.Column("pokt_avg", sa.DECIMAL(), nullable=False),
        sa.Column("relays_avg", sa.DECIMAL(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "chain_rewards_created_at_idx", "chain_rewards", ["created_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("chain_rewards_created_at_idx", table_name="chain_rewards")
    op.drop_table("chain_rewards")
    # ### end Alembic commands ###
