"""created runner_performance table

Revision ID: 06ddf4122e07
Revises: 
Create Date: 2022-12-08 17:15:37.252450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06ddf4122e07'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runner_performance',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('runner_domain', sa.String(), nullable=False),
    sa.Column('avg_last_48_hours', sa.DECIMAL(), nullable=False),
    sa.Column('avg_last_24_hours', sa.DECIMAL(), nullable=False),
    sa.Column('avg_last_6_hours', sa.DECIMAL(), nullable=False),
    sa.Column('total_chains', sa.BigInteger(), nullable=False),
    sa.Column('total_nodes', sa.BigInteger(), nullable=False),
    sa.Column('tokens', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')),
    sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')),
    sa.PrimaryKeyConstraint('id')
    )
    # add index to created_at
    op.create_index('runner_performance_created_at_idx',
                    'runner_performance', ['created_at'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('runner_performance')
    # ### end Alembic commands ###
