apiVersion: batch/v1
kind: CronJob
metadata:
  name: performance-monitoring
spec:
  schedule: "0 * * * *"
  successfulJobsHistoryLimit: 10
  concurrencyPolicy: Forbid
  suspend: true
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            runAsUser: 1000
          containers:
            - name: performance-monitoring
              image: sendnodes/performance-monitoring
              command:
                - python
                - ./main.py
                - -d
              envFrom:
                - secretRef:
                    name: performance-monitoring-secrets
          restartPolicy: Never
