---
name: "deploy"

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          branch: dev
          git_remote_url: "ssh://dokku@pokt-stats.sendnodes.io:22/pokt-scan-performance-monitoring"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
